config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :members
  resources :items
  post 'import_from_excel' => 'items#import_from_excel'
  post 'import_members' => 'members#import_from_excel'
  
  root to: 'members#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
  
  def full_name
    return "#{firstname} #{lastname}".strip if (firstname || lastname)
    "Anonymous"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    respond_to do |format|
      format.xlsx {
        response.headers['Content-Disposition'] = "attachment; filename='items.xlsx'"
      }
      format.html { render :index }
    end
  end
  
  def import_from_excel
    file = params[:file]
    begin
      # Retreive the extension of the file
      file_ext = File.extname(file.original_filename)
      raise "Unknown file type: #{file.original_filename}" unless [".xls", ".xlsx"].include?(file_ext)
      spreadsheet = (file_ext == ".xls") ? Roo::Excel.new(file.path) : Roo::Excelx.new(file.path)
      
      
      # header = spreadsheet.row(1)
      (6..spreadsheet.last_row).each do |i|
        Item.create(name: spreadsheet.row(i)[1], quantity: spreadsheet.row(i)[2])
      end
      flash[:notice] = "Records Imported"
      redirect_to root_path 
    rescue Exception => e
      flash[:notice] = "Issues with file"
      redirect_to root_path 
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :quantity)
    end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    # @members = Member.all
    
    @q = Member.ransack(params[:q])
    @members = @q.result(distinct: true)
    
  end
  
  def import_from_excel
    file = params[:file]
    begin
      # Retreive the extension of the file
      file_ext = File.extname(file.original_filename)
      raise "Unknown file type: #{file.original_filename}" unless [".xls", ".xlsx"].include?(file_ext)
      spreadsheet = (file_ext == ".xls") ? Roo::Excel.new(file.path) : Roo::Excelx.new(file.path)
      
      # Load Data
      (2..spreadsheet.last_row).each do |i|
        Member.create(
          member_id: spreadsheet.row(i)[0], 
          lastname: spreadsheet.row(i)[1],
          firstname: spreadsheet.row(i)[2],
          email: spreadsheet.row(i)[3]
          )
      end
      flash[:notice] = "Records Imported"
      redirect_to root_path 
    rescue Exception => e
      flash[:notice] = "Issues with file"
      redirect_to root_path 
    end
  end
  
  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:member_id, :lastname, :firstname, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/items_imports_helper.rb
module ItemsImportsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Import Form Excel</h1>
 <%= form_tag import_from_excel_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import", :class=> "btn" %>
<% end %>

<p id="notice"><%= notice %></p>

<h1>Items</h1>

<%=
  link_to 'Download as Excel',
  items_path(format: :xlsx)
%>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.quantity %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @item.quantity %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/_footer.html.erb
<footer>
  <p>&copy; Company 2018</p>
</footer>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-default navbar-static-top as-navbar-div">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "ExcelApp", root_path, :class => "navbar-brand" %>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      
      <ul class="nav navbar-nav">
        <li><%= link_to "Link1", "/path1"  %></li>
        <li><%= link_to "Link2", "/path2"  %></li>
        <li><%= link_to "Link3", "/path3"  %></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              Your Profile <%#= "Admin" if current_user.admin? %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit your profile", edit_user_registration_path(current_user) %></li>
              <!--<li><%#= link_to "View your profile", user_path(current_user) %></li>-->
              <li><a href="#">Your Messages</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Help</a></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", user_session_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>
        
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Excel App" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    
    <%= render 'layouts/navigation' %>

    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
      
      <%= render 'layouts/footer' %>
    </div> <!-- /container -->

  </body>
</html>

app/views/members/_form.html.erb
<%= form_for @member, :html => { :class => "form-horizontal member" } do |f| %>

  <% if @member.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @member.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :member_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :member_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:member_id) %>
  </div>
  <div class="form-group">
    <%= f.label :last_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :lastname, :class => 'form-control' %>
    </div>
    <%=f.error_span(:lastname) %>
  </div>
  <div class="form-group">
    <%= f.label :first_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :firstname, :class => 'form-control' %>
    </div>
    <%=f.error_span(:firstname) %>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                members_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/members/_import_from_excel.html.erb
<h4>Import Form Excel</h4>
 <%= form_tag import_members_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import", :class=> "btn" %>
<% end %>

app/views/members/edit.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/members/index.html.erb
<%= render 'members/import_from_excel' %>

<!--Ransack's search_form_for helper-->

<%= search_form_for @q, :html => { :class => "form-horizontal member" } do |f| %>

  <!--Search if the name field contains...-->
  <%= f.label "Search Name", :class => 'control-label col-lg-2' %>
  <%= f.search_field :firstname_or_lastname_cont, :class => 'form-control', :placeholder => "Enter name" %>

  <!--Search if an associated articles.title starts with...-->
  <%#= f.label :articles_title_start %>
  <%#= f.search_field :articles_title_start %>

  <!--Attributes may be chained. Search multiple attributes for one value...-->
  <%#= f.label :name_or_description_or_email_or_articles_title_cont %>
  <%#= f.search_field :name_or_description_or_email_or_articles_title_cont %>

  <%= f.submit nil, :class => 'btn btn-primary' %>
<% end %>

<!--end-->

<%- model_class = Member -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <!--<th>ID</th>-->
      <th>Member ID</th>
      <th>Full Name</th>
      <!--<th>Last Name</th>-->
      <!--<th>First Name</th>-->
      <th>Email</th>
      <!--<th>Created at</th>-->
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
      <tr>
        <!--<td><%#= link_to member.id, member_path(member) %></td>-->
        <td><%= link_to member.member_id, member_path(member) %></td>
        <td><%= member.full_name %></td>
        <!--<td><%#= member.lastname %></td>-->
        <!--<td><%#= member.firstname %></td>-->
        <td><%= member.email %></td>
        <!--<td><%#=l member.created_at %></td>-->
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_member_path(member), :class => 'btn btn-default btn-xs' %>
          <%= link_to "Show", member_path(member), :class => 'btn btn-xs btn-warning' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      member_path(member),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_member_path,
            :class => 'btn btn-primary' %>

app/views/members/new.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/members/show.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:member_id) %>:</strong></dt>
  <dd><%= @member.member_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lastname) %>:</strong></dt>
  <dd><%= @member.lastname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:firstname) %>:</strong></dt>
  <dd><%= @member.firstname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @member.email %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              members_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_member_path(@member), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              member_path(@member),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>